apiVersion: apps/v1
kind: Deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        importer: operate-importer
        app: camunda-platform
        app.kubernetes.io/component: operate
    spec:
      containers:
        - env:
            - name: ZEEBE_CLIENT_CONFIG_PATH
              value: /tmp/zeebe_auth_cache
            - name: CAMUNDA_OPERATE_IMPORTERENABLED
              value: "true"
            - name: CAMUNDA_OPERATE_ARCHIVERENABLED
              value: "false"
            - name: CAMUNDA_OPERATE_WEBAPPENABLED
              value: "true"
            - name: CAMUNDA_OPERATE_IMPORTER_THREADSCOUNT
              value: "6"
            - name: CAMUNDA_OPERATE_IMPORTER_READERTHREADSCOUNT
              value: "6"
            - name: CAMUNDA_OPERATE_CLUSTERNODE_NODECOUNT
              value: "3"
            - name: CAMUNDA_OPERATE_CLUSTERNODE_CURRENTNODEID
              value: "0"
            - name: CAMUNDA_OPERATE_ELASTICSEARCH_NUMBEROFSHARDS
              value: "5"
          image: camunda/operate:8.6.5
          imagePullPolicy: IfNotPresent
          name: operate
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /operate/actuator/health/readiness
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "7"
              memory: 4Gi
            requests:
              cpu: "7"
              memory: 2Gi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/local/operate/config/application.yml
              name: config
              subPath: application.yml
            - mountPath: /tmp
              name: tmp
            - mountPath: /camunda
              name: camunda
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 484
            name: camunda-operate-configuration
          name: config
        - emptyDir: {}
          name: tmp
        - emptyDir: {}
          name: camunda
  selector:
    matchLabels:
      importer: operate-importer
metadata:
  name: operate-importer-0
