apiVersion: v1
kind: Service
metadata:
  name: operate-importer-service
  namespace: camunda
  labels:
    app: camunda-platform
    app.kubernetes.io/component: operate
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: camunda-platform
    app.kubernetes.io/component: operate
    importer: operate-importer